### ISSUE TITLE
error:[Debug] Encountered an exception while sending help to CONSOLE

### ISSUE THREAD

**Issue by LeoFong** [MineSworn/SwornGuard#1]
[SwornGuard] [Debug] Encountered an exception while sending help to CONSOLE: net.dmulloy2.swornguard.exception.ReflectionException: JSON chat messages can only be sent to players.
Affected classes:
        net.dmulloy2.swornguard.chat.ChatUtil.sendMessageRaw(Line 88) [SwornGuard (2).jar]
        net.dmulloy2.swornguard.commands.CmdHelp.perform(Line 85) [SwornGuard (2).jar]
        net.dmulloy2.swornguard.commands.Command.execute(Line 159) [SwornGuard (2).jar]
        net.t7seven7t.swornguard.commands.jail.CmdJailHelp.perform(Line 29) [SwornGuard (2).jar]
        net.dmulloy2.swornguard.commands.Command.execute(Line 159) [SwornGuard (2).jar]
        net.dmulloy2.swornguard.commands.Command.onCommand(Line 94) [SwornGuard (2).jar]
        org.bukkit.command.PluginCommand.execute(Line 44) [craftbukkit_server.jar]
        org.bukkit.command.SimpleCommandMap.dispatch(Line 140) [craftbukkit_server.jar]
        org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(Line 621) [craftbukkit_server.jar]
        org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(Line 607) [craftbukkit_server.jar]
        java.lang.Thread.run(Native Method)

**Comment by dmulloy2** [comment]
This normal, which is why it's a debug message.
